<?php return array (
  1 => 
  array (
    'id' => '1',
    'tagfrom' => 'category',
    'default' => true,
    'catid' => '21',
    'titlenum' => '20',
    'custom' => 
    array (
      'link-font-size' => 
      array (
        'value' => '22px',
        'type' => 'text',
      ),
      'link-border-radius' => 
      array (
        'value' => '0px',
        'type' => 'text',
      ),
      'p-size' => 
      array (
        'value' => '14px',
        'type' => 'text',
      ),
    ),
    'title' => '栏目设置',
    'defaultDemo' => '1.default',
    'cn' => 
    array (
      'id' => '1',
      'tagfrom' => 'category',
      'default' => true,
      'catid' => '33',
      'titlenum' => '20',
      'title' => '栏目设置',
      'defaultDemo' => '1.default',
    ),
    'en' => 
    array (
      'id' => '1',
      'tagfrom' => 'category',
      'default' => true,
      'catid' => '83',
      'titlenum' => '20',
      'title' => 'Column setting',
      'defaultDemo' => '1.default',
    ),
    'jp' => 
    array (
      'id' => '1',
      'tagfrom' => 'category',
      'default' => true,
      'catid' => '118',
      'titlenum' => '20',
      'textnum' => '0',
      'title' => 'セクションの設定',
      'defaultDemo' => '1.default',
    ),
    'sk' => 
    array (
      'id' => '1',
      'tagfrom' => 'category',
      'default' => true,
      'catid' => '153',
      'titlenum' => '20',
      'title' => '프로그램 설정',
      'defaultDemo' => '1.default',
    ),
    'user' => 
    array (
      'id' => '1',
      'tagfrom' => 'category',
      'default' => true,
      'catid' => '83',
      'titlenum' => '20',
      'title' => '栏目设置',
      'defaultDemo' => '1.default',
    ),
  ),
  2 => 
  array (
    'id' => '2',
    'tagfrom' => 'content',
    'default' => true,
    'catid' => '21',
    'son' => '1',
    'typeid' => '0',
    'spid' => '0',
    'length' => '20',
    'introduce_length' => '60',
    'ordertype' => 'adddate-desc',
    'istop' => '0',
    'limit' => '3',
    'thumb' => 'on',
    'attr1' => '',
    'custom' => NULL,
    'title' => '内容列表设置',
    'defaultDemo' => '2.default',
    'cn' => 
    array (
      'id' => '2',
      'tagfrom' => 'content',
      'default' => true,
      'catid' => '33',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '内容列表设置',
      'defaultDemo' => '2.default',
    ),
    'en' => 
    array (
      'id' => '2',
      'tagfrom' => 'content',
      'default' => true,
      'catid' => '83',
      'son' => '1',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '60',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '3',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'Content list settings',
      'defaultDemo' => '2.default',
    ),
    'jp' => 
    array (
      'id' => '2',
      'tagfrom' => 'content',
      'default' => true,
      'catid' => '118',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'コンテンツリストの設定',
      'defaultDemo' => '2.default',
    ),
    'sk' => 
    array (
      'id' => '2',
      'tagfrom' => 'content',
      'default' => true,
      'catid' => '153',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '내용 리스트 설정',
      'defaultDemo' => '2.default',
    ),
    'user' => 
    array (
      'id' => '2',
      'tagfrom' => 'content',
      'default' => true,
      'catid' => '21',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '内容列表设置',
      'defaultDemo' => '2.default',
    ),
  ),
  3 => 
  array (
    'sk' => 
    array (
      'id' => 3,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '153',
      'titlenum' => '20',
      'title' => '프로그램 설정',
      'defaultDemo' => '1.default',
    ),
    'jp' => 
    array (
      'id' => 3,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '118',
      'titlenum' => '20',
      'textnum' => '0',
      'title' => 'セクションの設定',
      'defaultDemo' => '1.default',
    ),
    'en' => 
    array (
      'id' => 3,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '83',
      'titlenum' => '20',
      'title' => 'Column setting',
      'defaultDemo' => '1.default',
    ),
    'cn' => 
    array (
      'id' => '3',
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '33',
      'titlenum' => '20',
      'title' => '栏目设置',
      'defaultDemo' => '1.default',
    ),
    'custom' => 
    array (
      'link-font-size' => 
      array (
        'value' => '22px',
        'type' => 'text',
      ),
      'link-border-radius' => 
      array (
        'value' => '0px',
        'type' => 'text',
      ),
      'p-size' => 
      array (
        'value' => '14px',
        'type' => 'text',
      ),
    ),
  ),
  4 => 
  array (
    'sk' => 
    array (
      'id' => 4,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '153',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '내용 리스트 설정',
      'defaultDemo' => '2.default',
    ),
    'jp' => 
    array (
      'id' => 4,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '118',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'コンテンツリストの設定',
      'defaultDemo' => '2.default',
    ),
    'en' => 
    array (
      'id' => 4,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '83',
      'son' => '1',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '60',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '3',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'Content list settings',
      'defaultDemo' => '2.default',
    ),
    'cn' => 
    array (
      'id' => '4',
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '33',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '内容列表设置',
      'defaultDemo' => '2.default',
    ),
    'custom' => NULL,
  ),
  5 => 
  array (
    'sk' => 
    array (
      'id' => 5,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '153',
      'titlenum' => '20',
      'title' => '프로그램 설정',
      'defaultDemo' => '1.default',
    ),
    'jp' => 
    array (
      'id' => 5,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '118',
      'titlenum' => '20',
      'textnum' => '0',
      'title' => 'セクションの設定',
      'defaultDemo' => '1.default',
    ),
    'en' => 
    array (
      'id' => 5,
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '83',
      'titlenum' => '20',
      'title' => 'Column setting',
      'defaultDemo' => '1.default',
    ),
    'cn' => 
    array (
      'id' => '5',
      'tagfrom' => 'category',
      'default' => false,
      'catid' => '33',
      'titlenum' => '20',
      'title' => '栏目设置',
      'defaultDemo' => '1.default',
    ),
    'custom' => 
    array (
      'link-font-size' => 
      array (
        'value' => '22px',
        'type' => 'text',
      ),
      'link-border-radius' => 
      array (
        'value' => '0px',
        'type' => 'text',
      ),
      'p-size' => 
      array (
        'value' => '14px',
        'type' => 'text',
      ),
    ),
  ),
  6 => 
  array (
    'sk' => 
    array (
      'id' => 6,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '153',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '내용 리스트 설정',
      'defaultDemo' => '2.default',
    ),
    'jp' => 
    array (
      'id' => 6,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '118',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'コンテンツリストの設定',
      'defaultDemo' => '2.default',
    ),
    'en' => 
    array (
      'id' => 6,
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '83',
      'son' => '1',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '60',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '3',
      'thumb' => 'on',
      'attr1' => '',
      'title' => 'Content list settings',
      'defaultDemo' => '2.default',
    ),
    'cn' => 
    array (
      'id' => '6',
      'tagfrom' => 'content',
      'default' => false,
      'catid' => '33',
      'son' => '0',
      'typeid' => '0',
      'spid' => '0',
      'length' => '20',
      'introduce_length' => '200',
      'ordertype' => 'adddate-desc',
      'istop' => '0',
      'limit' => '',
      'thumb' => 'on',
      'attr1' => '',
      'title' => '内容列表设置',
      'defaultDemo' => '2.default',
    ),
    'custom' => NULL,
  ),
);